name: CMake Build (Ubuntu aarch64)

on:
  push:
    branches:
      - 0.9.5_CHN_remake
  pull_request:
    branches:
      - master

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-22.04-arm
    container: arm64v8/ubuntu:22.04

    steps:
    - name: Prepare system
      shell: bash
      run: |
        apt update
        apt -y full-upgrade
        apt -y install git
    - name: Check out source
      uses: actions/checkout@v4
    - name: Install dependencies
      shell: bash
      run: |
        dpkg --add-architecture arm64
        sh -c "sed \"s|^deb \([a-z\.:/]*\) \([a-z\-]*\) \(.*\)$|deb [arch=amd64] \1 \2 \3\ndeb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports \2 \3|\" /etc/apt/sources.list > /etc/apt/sources.list.new"
        rm /etc/apt/sources.list
        mv /etc/apt/sources.list{.new,}
        apt update
        DEBIAN_FRONTEND=noninteractive apt install -y {gcc,g++}-aarch64-linux-gnu pkg-config {libsdl2,qtbase5,qtbase5-private,qtmultimedia5,libslirp,libarchive}-dev:arm64 cmake extra-cmake-modules dpkg-dev
    - name: Configure
      shell: bash
      run: |
        CC=aarch64-linux-gnu-gcc CXX=aarch64-linux-gnu-g++ cmake -DPKG_CONFIG_EXECUTABLE=/usr/bin/aarch64-linux-gnu-pkg-config $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -B build
    - name: Make
      shell: bash
      run: |
        cmake --build build -j$(nproc --all)
        mkdir dist
        cp build/melonDS dist
    - uses: actions/upload-artifact@v4
      with:
        name: melonDS-ubuntu-aarch64
        path: dist
